config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create, :new] 
      resources :likes, only: [:create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
  root	'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comment_counter

  def update_comment_counter
    post.update(comments_counter: post.comments.all.length)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_like_counter

  def update_like_counter
    post.update(likes_counter: post.likes.all.length)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, foreign_key: :post_id
  has_many :comments, foreign_key: :post_id

  validates :title, presence: true, length: { minimum: 3, maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :name, presence: true
  validates :postscounter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def most_recent_posts
    posts.first(3)
  end
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules.Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to user_post_path(current_user, @comment.post)
    else
      render :create
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new
    @like.post_id = params[:post_id]

    if @like.save
      redirect_to user_post_path(current_user, @like.post)
    else
      render :create
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.includes(:comments, :likes).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      flash[:success] = 'Your Post has benn created successfully'
      redirect_to user_post_path(current_user, @post)
    else
      flash.now[:error] = 'Error message: Post was not created !'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_add_comment.html.erb
<%= form_with model: Comment, url: user_post_comments_path(@post.author, @post) do |form| %>
     <div>
       <%= form.label 'Add a comment' %> <br>
       <%= form.text_area :text, placeholder: "Type In comment", row: 20, required: true %>
     </div>

     <div> 
       <%= form.submit "Comment" %>
     </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='container mt-4'>
  <%= render 'navbar/header' %> 
  <p class="notice"><%= notice</p> %>  
  <p class="alert"><%= alert</p>  %>
    <%= yield %> %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script> %> %>
  </body>
</html>

app/views/likes/_add_like.html.erb
<section>
  <%= form_with model: Like, url: user_post_likes_path(@post.author, @post) do |form| %>
     <%= form.submit 'Like Post' %>
     <% end %>

</section>

app/views/navbar/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
  <%= link_to 'Home', root_path, class: "navbar-brand text-white" %>
  <% if user_signed_in? %>
    <%= button_to t('sign_out'), destroy_user_session_path, method: :delete %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="#">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Link</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/posts/index.html.erb
<section>
  <div class='single-user'>
    <div class='user-photo'>
      <img src='<%= @user.photo %>' alt='<%= @user.name %> thumbnail' />
    </div>
    <div class='user-name'>
      <h2><%= @user.name %></h2>
      <p>Number of Posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <h4><%= link_to 'Add new Post', new_user_post_path %></h4>
  <div class='user-posts'>
    <% @user.posts.each do |post| %>
      <div class='list-posts'>
        <h5><%= link_to post.title, user_post_path(@user, post) %></h5>
        <p><%= post.text %></p>
        <span class='like-comment'>
          Comments: <%= post.comments_counter || 0 %>, 
          Likes: <%= post.likes_counter || 0 %> 
        </span>
      </div>
      <ul class='post-comment'>
        <% if post.five_recent_comments.length == 0 %>
          <p>No comments added!</p>
        <% else %>
          <% post.five_recent_comments.each do |comment| %>
            <li><%= comment.author.name %>: <%= comment.text %></li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<section class="container">
<p class="post-title"> Create New Post :</p>
<%= form_with model: @post, url: user_posts_path do |form| %>
     <div>
     <%= form.label :title %> <br>
     <%= form.text_field :title %>
     </div>

     <div>
     <%= form.label :text %> <br>
     <%= form.text_field :text %>
     </div>
     <br>
     <div>
     <%= form.submit "Submit Post" %>
     </div>
<% end %>

</section>

app/views/posts/show.html.erb
<section>
  <div class='list-posts'>
    <h3><%= @post.title %> by <%= @post.author.name %> </h3>
    <p><%= @post.text %></p>
    <span class='like-comment'>
      Comments: <%= @post.comments_counter || 0 %>, 
      Likes: <%= @post.likes_counter || 0 %> 
    </span>
  </div>
  <ul class='post-comment'>      
    <% if @post.comments.length == 0 %>
      <p>No comments added!</p>
    <% else %>
      <% @post.comments.each do |comment| %>
        <li><%= comment.author.name %>: <%= comment.text %></li>
      <% end %>
    <% end %>
  </ul>
  <div>
  <%= render "likes/add_like" %>
  </div>
  <%= render "comments/add_comment" %>
</section>

app/views/users/index.html.erb
<section>
  <ul class='user-container'>
    <% @users.each do |user| %>
      <li class='user'>
        <% if user.photo %>
          <img src='<%= user.photo %>' alt='<%= user.name %> thumbnail' />
        <% end %>
        <div class='user-name'>
          <h2><%= link_to user.name, user_path(user) %></h2>
          <p>Number of Posts: <%= user.posts_counter %></p>
        </div>
      </li>
    <% end %>
  </ul>
</section>

app/views/users/show.html.erb
<section>
  <div class='one-user'>
    <div class='user-photo'>
      <% if @user.photo %>
        <img class="card-img-top" src='<%= @user.photo %>' alt='<%= @user.name %> thumbnail' />
      <% end %>
    </div>
    <div class='user-name'>
      <h2><%= @user.name %></h2>
      <p>Number of Posts: <%= @user.posts_counter || 0 %></p>
    </div>
  </div>
  <div class='user-bio'>
    <h4>Bio</h4>
    <h5><%= @user.bio %></h5>
  </div>
  <div class='posts'>
    <% @user.three_most_recent_post.each do |post| %>
      <div class='list-posts'>
        <h5><%= link_to post.title, user_post_path(@user, post) %></h5>
        <p><%= post.text %></p>
        <span class='like-comment'>
          Comments: <%= post.comments_counter || 0 %>, 
          Likes: <%= post.likes_counter || 0 %> 
        </span>
      </div>
    <% end %>
  </div>
  <button class='see-btn'>
    <%= link_to 'see all posts', user_posts_path(@user) %>
  </button>
</section>